# Generated by Django 3.2.13 on 2023-04-02 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('bag_file', models.FileField(blank=True, null=True, upload_to='bag_files')),
                ('rgb_video', models.FileField(blank=True, null=True, upload_to='rgb_video')),
                ('depth_video', models.FileField(blank=True, null=True, upload_to='depth_video')),
                ('parsed_video', models.FileField(blank=True, null=True, upload_to='parsed_video')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
