# Generated by Django 3.2.13 on 2023-04-02 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comp_vision', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='bag_file',
            field=models.FileField(blank=True, null=True, upload_to='bag_files/'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='depth_video',
            field=models.FileField(blank=True, null=True, upload_to='depth_video/'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='parsed_video',
            field=models.FileField(blank=True, null=True, upload_to='parsed_video/'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='rgb_video',
            field=models.FileField(blank=True, null=True, upload_to='rgb_video/'),
        ),
    ]
