# Generated by Django 3.2.13 on 2023-04-12 09:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comp_vision', '0002_auto_20230402_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='cnt_man',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='videos',
            name='bag_file',
            field=models.FileField(blank=True, null=True, upload_to='bag_files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'bag'])]),
        ),
    ]
